# Copyright 2018 ConsenSys AG.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Project information
site_name: Pantheon
site_url: https://docs.pantheon.pegasys.tech/en/stable/
site_description: Pantheon Java Ethereum client documentation.
site_author: Pantheon community
copyright: Pantheon and its documentation are licensed under Apache 2.0 license /
  This <a href="https://readthedocs.org/">Readthedocs.org</a> documentation is maintained with love by <a href="https://pegasys.tech/">PegaSys</a>.

#extra project info and template customisation
extra:
  versions:
    pantheon_stable: &pantheon_stable_version 1.1.4
    quickstart: *pantheon_stable_version
  latest_version_warning:
    url_contains: /latest/
    text: 'You are reading Pantheon development version documentation and
    some displayed features may not be available in the stable release.
    You can switch to stable version using the version box at screen bottom.'
  support:
    gitter: https://gitter.im/PegaSysEng/pantheon
    email: support@pegasys.tech
    pegasys_website: https://pegasys.tech/
    issues: https://pegasys1.atlassian.net/secure/Dashboard.jspa?selectPageId=10000
  google:
    site_verification: 'za1cLzyS6LXDGO-pMzvfQdYTZ0Zc67uZtY0asA4YXZ0'
    tag_manager: 'GTM-5B7N84J'
  search:
    language: 'en'
    tokenizer: '[\s]+'

# Repository
repo_name: PegaSysEng/pantheon
repo_url: https://github.com/PegaSysEng/pantheon/

theme:
    name: material
    custom_dir: docs/custom_theme
    palette:
        primary: blue-grey
        accent: teal
    favicon: favicon.ico
    logo:
      icon: account_balance
nav:
    - Installation:
        - Installation Overview: Installation/Overview.md
        - Install Binary Distribution: Installation/Install-Binaries.md
        - Build from Source: Installation/Build-From-Source.md
        - System Requirements: Installation/System-Requirements.md
    - Architecture:
        - Overview: Architecture/Overview.md
    - Getting Started:
        - Getting Started Overview: Getting-Started/Getting-Started.md
        - Starting Pantheon: Getting-Started/Starting-Pantheon.md
        - Running Pantheon from Docker Image: Getting-Started/Run-Docker-Image.md
    - Tutorials:
        - Private Network Quickstart: Tutorials/Private-Network-Quickstart.md
        - Private Network Quickstart for Private Transactions: Tutorials/Privacy-Quickstart.md
        - Private Network Quickstart On Azure: Tutorials/Azure/Azure-Private-Network-Quickstart.md
        - Create a Private Network using Ethash (Pow): Tutorials/Create-Private-Network.md
        - Create a Private Network using Clique (PoA): Tutorials/Create-Private-Clique-Network.md
        - Create a Private Network using IBFT 2.0 (PoA): Tutorials/Create-IBFT-Network.md
        - Create a Permissioned Network: Tutorials/Create-Permissioned-Network.md
    - Pantheon API:
        - Overview: Pantheon-API/Pantheon-API.md
        - JSON-RPC over HTTP or WebSockets: Pantheon-API/Using-JSON-RPC-API.md
        - RPC Pub/Sub over WebSockets: Pantheon-API/RPC-PubSub.md
        - GraphQL over HTTP: Pantheon-API/GraphQL.md
        - Authentication: Pantheon-API/Authentication.md
    - Configuring Pantheon:
        - Network vs Node Configuration: Configuring-Pantheon/Network-vs-Node.md
        - Configuration File: Configuring-Pantheon/Using-Configuration-File.md
        - Configuration Items in Genesis File: Configuring-Pantheon/Config-Items.md
        - Network ID and Chain ID: Configuring-Pantheon/NetworkID-And-ChainID.md
        - Free Gas Networks: Configuring-Pantheon/FreeGas.md
        - Contracts in Genesis: Configuring-Pantheon/Contracts-in-Genesis.md
        - Node Keys: Configuring-Pantheon/Node-Keys.md
        - Accounts for Testing: Configuring-Pantheon/Accounts-for-Testing.md
        - Passing JVM Options: Configuring-Pantheon/Passing-JVM-Options.md
    - Networking:
      - Bootnodes: Configuring-Pantheon/Networking/Bootnodes.md
      - Configuring Ports: Configuring-Pantheon/Networking/Configuring-Ports.md
      - Managing Peers: Configuring-Pantheon/Networking/Managing-Peers.md
      - Using UPnP: Configuring-Pantheon/Networking/Using-UPnP.md
    - Consensus Protocols:
      - Pantheon Consensus Protocols: Consensus-Protocols/Overview-Consensus.md
      - Comparing PoA Consensus Protocols: Consensus-Protocols/Comparing-PoA.md
      - Clique: Consensus-Protocols/Clique.md
      - IBFT 2.0: Consensus-Protocols/IBFT.md
      - Quorum IBFT 1.0: Consensus-Protocols/QuorumIBFT.md
    - Privacy:
        - Tutorials:
          - Configuring a Privacy-Enabled Network: Privacy/Tutorials/Configuring-Privacy.md
          - Using web3.js-eea Multinode Example: Privacy/Tutorials/eeajs-Multinode-example.md
        - How To:
          - Use EEA-compliant Privacy: Privacy/How-To/EEA-Compliant.md
          - Use Pantheon-extended Privacy: Privacy/How-To/Pantheon-Privacy.md
          - Create and Send Private Transactions: Privacy/How-To/Creating-Sending-Private-Transactions.md
          - Create and Manage Privacy Groups: Privacy/How-To/Create-Manage-Privacy-Groups.md
          - Access Private and Privacy Marker Transactions: Privacy/How-To/Access-Private-Transactions.md
          - Use the web3.js-eea Client Library: Privacy/How-To/eeajs.md
        - Explanation:
          - Privacy Overview: Privacy/Explanation/Privacy-Overview.md
          - Privacy Groups: Privacy/Explanation/Privacy-Groups.md
          - Processing Private Transactions: Privacy/Explanation/Private-Transaction-Processing.md
    - Permissioning:
        - Overview: Permissions/Permissioning-Overview.md
        - Local Permissioning: Permissions/Local-Permissioning.md
        - Onchain Permissioning:
            - Overview: Permissions/Onchain-Permissioning/Onchain-Permissioning.md
            - Getting Started with Onchain Permissioning: Permissions/Onchain-Permissioning/Getting-Started-Onchain-Permissioning.md
            - Deploying Management Dapp for Production: Permissions/Onchain-Permissioning/Production.md
            - Updating Whitelists: Permissions/Onchain-Permissioning/Updating-Whitelists.md
    - Using Pantheon:
        - Transactions:
          - Creating and Sending Transactions: Using-Pantheon/Transactions/Transactions.md
          - Transaction Pool: Using-Pantheon/Transactions/Transaction-Pool.md
          - Vadidating Transactions: Using-Pantheon/Transactions/Transaction-Validation.md
          - Including Revert Reason: Using-Pantheon/Transactions/Revert-Reason.md
        - Using Truffle with Pantheon: Using-Pantheon/Truffle.md
        - Events and Logs:
          - Overview: Using-Pantheon/Events-and-Logs.md
          - Accessing Logs Using JSON-RPC API: Using-Pantheon/Accessing-Logs-Using-JSON-RPC.md
        - Using Wallets for Account Management: Using-Pantheon/Account-Management.md
        - Mining: Using-Pantheon/Mining.md
    - Monitoring:
        - Logging: Monitoring/Logging.md
        - Monitoring Performance: Monitoring/Monitoring-Performance.md
        - Monitoring Network:
          - Alethio Overview: Monitoring/Alethio/Overview.md
          - Alethio Ethereum Lite Explorer: Monitoring/Alethio/Lite-Block-Explorer.md
          - Alethio EthStats Lite Network Monitor: Monitoring/Alethio/Lite-Network-Monitor.md
    - Deploying Pantheon:
        - Ansible: Deploying-Pantheon/Ansible.md
        - High Availability of APIs: Deploying-Pantheon/High-Availability.md
        - Migrating Docker Image: Deploying-Pantheon/Migration-Docker.md
    - Troubleshooting:
        - Troubleshooting: Troubleshooting/Troubleshooting.md
    - Reference:
        - Pantheon Command Line: Reference/Pantheon-CLI-Syntax.md
        - Pantheon API Methods: Reference/Pantheon-API-Methods.md
        - Pantheon API Objects: Reference/Pantheon-API-Objects.md
        - web3.js-eaa Methods: Reference/web3js-eea-Methods.md
    - Resources:
        - Blog Posts and Webinars: Resources/Resources.md

markdown_extensions:
    - toc:
        permalink: 
        toc_depth: 3
    - codehilite
    - markdown_include.include:
        base_path: docs
    - admonition
    - footnotes
    - def_list
    - abbr
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - meta
    - smarty

plugins:
    - search
    - markdownextradata
    - exclude:
        glob:
          - development/*
          - community/*
          - global/*